CREATE TABLE IF NOT EXISTS ai_research_reports (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  session_id BIGINT NOT NULL,
  run_id BIGINT NOT NULL,
  final_message_id BIGINT NOT NULL,
  idempotency_key VARCHAR(64) NOT NULL,
  title VARCHAR(120) NOT NULL,
  notes VARCHAR(1000) NULL,
  result_json JSON NOT NULL,
  citation_manifest_json JSON NOT NULL,
  evidence_version VARCHAR(128) NOT NULL,
  data_version VARCHAR(128) NULL,
  source_session_available TINYINT(1) NOT NULL DEFAULT 1,
  status VARCHAR(24) NOT NULL DEFAULT 'active',
  revision BIGINT NOT NULL DEFAULT 1,
  trashed_at DATETIME(6) NULL,
  purge_after DATETIME(6) NULL,
  purged_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uk_ai_research_reports_user_idempotency (user_id, idempotency_key),
  KEY idx_ai_research_reports_owner_status (user_id, status, updated_at, id),
  KEY idx_ai_research_reports_purge (status, purge_after),
  CONSTRAINT chk_ai_research_reports_status CHECK (status IN ('active','trash','permanently_purged')),
  CONSTRAINT chk_ai_research_reports_revision CHECK (revision > 0)
) ENGINE=InnoDB;
